%include	/usr/lib/rpm/macros.perl
Summary:	Tool for flexible configuration software packages
Summary(pl.UTF-8):	Narzędzie do łatwego konfigurowania pakietów
Name:		itchconfig
Version:	0.0.4
Release:	1
License:	GPL
Group:		Development/Building
Source0:	http://dl.sourceforge.net/%{name}/%{name}-%{version}.tar.gz
# Source0-md5:	fd10a534c3a845f07cac8be8c301e266
URL:		http://itchconfig.sourceforge.net/
BuildRequires:	m4 >= 1.3
BuildRequires:	rpm-perlprov
BuildArch:	noarch
BuildRoot:	%{tmpdir}/%{name}-%{version}-root-%(id -u -n)

%description
itchconfig is a tool for the flexible, non-interactive configuration
of software packages on Unix-like operating systems. Similar to the
GNU autoconf/automake tools, a configure script  generated by
itchconfig checks several properties  of a user's computer (C
compiler, libraries, ...) and generates all files (e.g. the Makefile)
which are necessary to build an executable program from the source
code of a software package on the user's computer.

%description -l pl.UTF-8
itchconfig jest narzędziem do łatwego, nieinteraktywnego ustawiania
konfiguracji pakietów na systemach uniksowych. Podobnie jak w
przypadku narzędzi GNU autoconf/automake skrypt configure wygenerowany
przez itchconfig sprawdza kilka własności komputera użytkownika
(kompilator C, biblioteki...) oraz generuje wszystkie pliki (np.
Makefile) potrzebne do zbudowania wersji wykonywalnej programu ze
źródeł na komputerze użytkownika.

%prep
%setup -q

%build
./configure \
	--path-prefix=%{_prefix} \
	--path-man=%{_mandir} \
	--path-info=%{_infodir}
%{__make}

%install
rm -rf $RPM_BUILD_ROOT
install -d $RPM_BUILD_ROOT{%{_bindir},%{_datadir}/itchconfig}
install -d $RPM_BUILD_ROOT{%{_mandir}/man1,%{_infodir},%{perl_vendorlib}}
install itchconfig itchscan $RPM_BUILD_ROOT%{_bindir}
install itchlib.pm itchcop.pm $RPM_BUILD_ROOT%{perl_vendorlib}
install itchconfig.m4 $RPM_BUILD_ROOT%{_datadir}/itchconfig
install docu/itchconfig.1 docu/itchscan.1 $RPM_BUILD_ROOT%{_mandir}/man1
install docu/itchconfig.info $RPM_BUILD_ROOT%{_infodir}

%clean
rm -rf $RPM_BUILD_ROOT

%post
[ ! -x /usr/sbin/fix-info-dir ] || /usr/sbin/fix-info-dir -c %{_infodir} >/dev/null 2>&1

%postun
[ ! -x /usr/sbin/fix-info-dir ] || /usr/sbin/fix-info-dir -c %{_infodir} >/dev/null 2>&1

%files
%defattr(644,root,root,755)
%doc docu/*.html README INSTALL
%attr(755,root,root) %{_bindir}/*
%dir %{_datadir}/%{name}
%{_datadir}/%{name}/*
%{_mandir}/man1/*
%{_infodir}/*
%{perl_vendorlib}/*
